/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as ArrivalRouteImport } from './routes/arrival'
import { Route as ClubRouteImport } from './routes/club'
import { Route as MasterplanRouteImport } from './routes/masterplan'
import { Route as ResortRouteImport } from './routes/resort'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as VillasRouteImport } from './routes/villas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrivalRoute = ArrivalRouteImport.update({
  id: '/arrival',
  path: '/arrival',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterplanRoute = MasterplanRouteImport.update({
  id: '/masterplan',
  path: '/masterplan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResortRoute = ResortRouteImport.update({
  id: '/resort',
  path: '/resort',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const VillasRoute = VillasRouteImport.update({
  id: '/villas',
  path: '/villas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/arrival': typeof ArrivalRoute
  '/club': typeof ClubRoute
  '/masterplan': typeof MasterplanRoute
  '/resort': typeof ResortRoute
  '/revenue': typeof RevenueRoute
  '/villas': typeof VillasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/arrival': typeof ArrivalRoute
  '/club': typeof ClubRoute
  '/masterplan': typeof MasterplanRoute
  '/resort': typeof ResortRoute
  '/revenue': typeof RevenueRoute
  '/villas': typeof VillasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/arrival': typeof ArrivalRoute
  '/club': typeof ClubRoute
  '/masterplan': typeof MasterplanRoute
  '/resort': typeof ResortRoute
  '/revenue': typeof RevenueRoute
  '/villas': typeof VillasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/amenities'
    | '/arrival'
    | '/club'
    | '/masterplan'
    | '/resort'
    | '/revenue'
    | '/villas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/amenities'
    | '/arrival'
    | '/club'
    | '/masterplan'
    | '/resort'
    | '/revenue'
    | '/villas'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/amenities'
    | '/arrival'
    | '/club'
    | '/masterplan'
    | '/resort'
    | '/revenue'
    | '/villas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AmenitiesRoute: typeof AmenitiesRoute
  ArrivalRoute: typeof ArrivalRoute
  ClubRoute: typeof ClubRoute
  MasterplanRoute: typeof MasterplanRoute
  ResortRoute: typeof ResortRoute
  RevenueRoute: typeof RevenueRoute
  VillasRoute: typeof VillasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrival': {
      id: '/arrival'
      path: '/arrival'
      fullPath: '/arrival'
      preLoaderRoute: typeof ArrivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masterplan': {
      id: '/masterplan'
      path: '/masterplan'
      fullPath: '/masterplan'
      preLoaderRoute: typeof MasterplanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resort': {
      id: '/resort'
      path: '/resort'
      fullPath: '/resort'
      preLoaderRoute: typeof ResortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villas': {
      id: '/villas'
      path: '/villas'
      fullPath: '/villas'
      preLoaderRoute: typeof VillasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AmenitiesRoute: AmenitiesRoute,
  ArrivalRoute: ArrivalRoute,
  ClubRoute: ClubRoute,
  MasterplanRoute: MasterplanRoute,
  ResortRoute: ResortRoute,
  RevenueRoute: RevenueRoute,
  VillasRoute: VillasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
